# -*- coding: utf-8 -*-
"""password strength checker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rBJhj0ZNWH3VMYCQjokZ86IYT0lA9WQU
"""

def check_password_strength(password):
    score = 0
    comments = []

    if len(password) >= 8:
        score += 1
    else:
        comments.append("Password is too short. Try making it at least 8 characters.")


    if any(c.islower() for c in password):
        score += 1
    else:
        comments.append("Add some lowercase letters for a stronger password.")

    if any(c.isupper() for c in password):
        score += 1
    else:
        comments.append("Try adding uppercase letters to improve security.")

    if any(c.isdigit() for c in password):
        score += 1
    else:
        comments.append("Throw in a number or two for extra strength.")

    if any(c in "!@#$%^&*()_+" for c in password):
        score += 1
    else:
        comments.append("Add some special characters .")

    if score == 5:
        comments.append("Your password is strong!")
    elif score >= 3:
        comments.append("Your password is decent, but could be stronger.")
    else:
        comments.append("Your password is weak. ⚠️")

    return "\n".join(comments)


def password_checker():
    password = input("Enter your password: ")
    result = check_password_strength(password)
    print(result)

password_checker()

"""run the program"""